### ISSUE TITLE
If we have a pilot version of the KB - how can team members view it

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/KnowledgeBase#31]
On the development machine, it would be nice to have a basic web site  (e.g., PHP), that can run
select * from summary_table
select * from detailed_table

Otherwise all of us would have to login to the db machine which is not realistic.

in other words, super early pilot KB viewer

**Comment by rkboyce** [comment]
Closing this issue. Lee Evans or myself can help folks get access to the DB from their local machine using the postgres client "PGAdmin 3".
