### ISSUE TITLE
Need New Vocabualry

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/KnowledgeBase#53]
Sometime the week for 4/06/2015 there will be another release of the V5 Vocabulary.  We need this for  its improved hierarchies.  

@leeevans  will most likely load the updated Vocabulary into the Postgres public environment when it is ready.  Then @rkboyce will need to reload the Laertes processing once we have this Vocabulary.

**Comment by cgreich** [comment]
The release is coming out tomorrow or Friday.

**Comment by ericaVoss** [comment]
This has been completed.
