### ISSUE TITLE
Update the OMOP Reference Set

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/KnowledgeBase#54]
Noticed some duplication in the Reference set.  Need to figure out why and eliminate issue and reload reference set tables.

This is for @ericaVoss.

**Comment by cgreich** [comment]
What's a reference set?

**Comment by ericaVoss** [comment]
The OMOP Reference set (e.g. HOI = GI Bleed with +/- controls)

**Comment by cgreich** [comment]
You mean the HOI and DOI cohort concepts? They are back in. In fact, they were just not clicked by default. I am going to change that, and the "Cohort" vocabulary will be clicked by default.

**Comment by cgreich** [comment]
Ouch. :)

Anyway. they need to be cleaned up big time anyway.

**Comment by ericaVoss** [comment]
This has been fixed.
