### ISSUE TITLE
Splicer Results

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/KnowledgeBase#55]
@rkboyce - Separate out the two sections for Splicer instead of having an aggregate result.

34066-1 - FDA package insert Boxed warning section
34084-4 – FDA package insert Adverse reactions section

**Comment by ericaVoss** [comment]
Also, how hard would it be to also add 43685-7 - WARNINGS AND PRECAUTIONS SECTION or would it take additional work with Jon.

**Comment by rkboyce** [comment]
Done  - only Precautions and ADRs because Jon does not feel confident in the results for other sections as yet
