### ISSUE TITLE
Incorrect Evidence Link Out

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/KnowledgeBase#59]
@rkboyce the EVIDENCE_LINKOUT for AERS_REPORT_COUNT is to a pubmed article.

```{sql}
SELECT *
FROM DRUG_HOI_EVIDENCE
WHERE DRUG_HOI_RELATIONSHIP = '1363053-137829'
```

---------------

```{txt}
678452;"1363053-137829";"aers_report_count";t;5;9807;"http://www.ncbi.nlm.nih.gov/pubmed/22422992";"COUNT"
678453;"1363053-137829";"aers_report_PRR";t;5;0.952024246779733;"http://www.ncbi.nlm.nih.gov/pubmed/22422992";"AERS_PRR"

```

**Comment by rkboyce** [comment]
That is the linkout  I intended because we don't have operationalized a way to 'drill down' into FAERS. For further development of this resource, we might look closely at the OpenFDA API into FAERS: https://open.fda.gov/drug/event/ 

What do you think?

**Comment by ericaVoss** [comment]
Well, if we get Vigibase, AERS will not be necessary and we already have traction with Vigibase.  Maybe it isn't worth it building this functionality now.

Are the PubMed URLs you are passing are they even applicable?  If not, I would just say the link out is NULL.

**Comment by rkboyce** [comment]
OpenFDA could still be interesting because any meaningful interaction with Vigibase is going to require a license which allot of academics will not be able to afford. So, lets hold on to the thought anyway.

**Comment by rkboyce** [comment]
We should also explore OpenPHACTs: 

OpenPHACTS v.1.5 has just added AERS:
https://dev.openphacts.org/docs/1.5

Also noticed their pathway explorer. Here's an example:
https://explorer2.openphacts.org/compounds/pathways?uri=http%3A%2F%2Fidentifiers.org%2Fhmdb%2FHMDB00099




In general, there is probably a great deal of synergy between this project and OpenPHACTS

**Comment by rkboyce** [comment]
This needs to get fixed in the next update of LAERTES so that the WebApi drill down calls function consistently.
