### ISSUE TITLE
Overall MEDLINE Count

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/KnowledgeBase#60]
Right now we break MEDLINE into MEDLINE_CT, MEDLINE_CASE, and MEDLINE_OTHER.  It would be good to have a MEDLINE (this is a count of publications without being parsed).  In most cases MEDLINE_CT + MEDLINE_CASE + MEDLINE_OTHER = MEDLINE but there is always the opportunity for overlap.

**Comment by rkboyce** [comment]
Check that the "MEDLINE OTHER" is actually excluding indexes with CT and CASE pub types

**Comment by ericaVoss** [comment]
In the [query](https://github.com/OHDSI/KnowledgeBase/blob/96116a5ef62a5f67d142524a6badf32100c296c9/LAERTES/PubMed/queryDrugHOIAssociations.psql), we are restricting to things that are  `('Case Reports','Clinical Trial','Meta-Analysis')`, so the only thing in "OTHER" is 'Meta-Analysis'.
