### ISSUE TITLE
MI Missing From Universe

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/KnowledgeBase#65]
The data requirements applied to LAERTES end up removing many MI SNOMED conditions, need to figure out what causes the drop out.

**Comment by rkboyce** [comment]
This is not a LAERTES but - rather, it is an issue to be addressed using the Vocab and semantic Similarity

**Comment by cgreich** [comment]
@ericaVoss: How do they get mapped in? Through MedDRA? Are you using the latest release with the updated MedDRA to SNOMED mappings?

**Comment by ericaVoss** [comment]
@cgreich - I figured out the problem, some of our sources are going MeSH --> SNOMED and some are going MedDRA --> SNOMED.  This means for some conditions, like MI, they just land in different SNOMED concepts.  I'm defining a "Laertes Universe" and I just need to do it a different way than I was.
