### ISSUE TITLE
LAERTES Version

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/KnowledgeBase#78]
We need to start a version number system on LAERTES.  

I would suggest something similar to the VOCAB.  The date usually ends up being most important as minor releases don't happen that often.
`[major version].[minor version].[DATE]`

So for example, we had a 1.00.Some Date, then a 2.00.Some Date, but we did a minor version update prior to PENELOPE, putting us at our current version 2.01.20151016

Just like with the VOCAB the version you have will dictate many things.  For example if we build a model off of LAERTES that model will only be good for 1 version of LAERTES.

**Comment by ericaVoss** [comment]
You could follow the VOCAB model and put it in the EVIDENCE table.

**Comment by ericaVoss** [comment]
I believe that our current release is 3.01.20160412.

**Comment by ericaVoss** [comment]
Next version will be 3.02.DATE

**Comment by ericaVoss** [comment]
Added this to ohdsiTest3.psql.

```{sql}
INSERT INTO evidence_sources 
VALUES (0,'LAERTES','Largescale Adverse Effects Related to Treatment Evidence Standardization v3.01.20160909','KnowledgeBase','OHDSI','2016-09-09','http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi#the_laertes_evidence_service','','1900-01-01','2016-09-09'),
```

This is assuming a Sept 09 release.  Wanted to get your thoughts before I added this to the table.

**Comment by rkboyce** [comment]
This change will not be up on the public server until the next full update, most likely January 2017

**Comment by ericaVoss** [comment]
I think we are targeting 3.01.20161021

```{SQL}
INSERT INTO evidence_sources 
VALUES (0,'LAERTES','Largescale Adverse Effects Related to Treatment Evidence Standardization v3.01.20161021','KnowledgeBase','OHDSI','2016-10-21','http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi#the_laertes_evidence_service','','1900-01-01','2016-10-21'),
```

I should create a new pull request and update this line.
https://github.com/OHDSI/KnowledgeBase/blob/731d7b508a417631a0c543d36a716f9f3d4ea2c3/LAERTES/Schema/postgresql/ohdsiTest3.psql#L117
