### ISSUE TITLE
Drop CDM only Tables

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/KnowledgeBase#89]
I'd like to suggest dropping the CDM only tables.  They just clutter the database.  They could be added to a post processing step.

**Comment by ericaVoss** [comment]
I think there is SynPUF data in there, I have an email out to @leeevans.

Asked @leeevans  to drop the following:
```{sql}
DROP TABLE LU_REF_SET_DRUG_HOI_DEF_DELETEME;
DROP TABLE LU_REF_SET_HOI_DEF_DELETEME;
DROP TABLE LU_AZ_CERT_DELETEME;
```

I ran the following:
```{sql}
DROP TABLE temp_drug_hoi_evidence_ingredient
DROP TABLE temp_laertes_condition_universe
DROP TABLE temp_laertes_drug_universe
DROP TABLE temp_lu_condition_children
DROP TABLE temp_lu_conditions
```

**Comment by ericaVoss** [comment]
Before I do something stupid @anthonysena and @leeevans can you guys give a quick review of this list of CDM tables that are okay to delete?

```{text}
care_site
cdm_source
cohort
cohort_attribute
condition_era
condition_occurrence
death
device_cost
device_exposure
dose_era
drug_cost
drug_era
drug_exposure
fact_relationship
location
measurement
note
observation
observation_period
payer_plan_period
person
procedure_cost
procedure_occurrence
provider
specimen
visit_cost
visit_occurrence
```

@rkboyce, @leeevans & @anthonysena, 

these were the tables I wasn't sure about:

```{text}
concept_cpt4
ctgov_drug_trials
faers_standard_drug_outcome_drilldown
faers_standard_drug_outcome_statistics
meddrapt_to_snomed
missing_cpt4
multi
target
```

**Comment by leeevans** [comment]
Hi @ericaVoss 

Please keep the following tables:

1) faers_standard_drug_outcome_drilldown
2) faers_standard_drug_outcome_statistics
3) meddrapt_to_snomed

1 & 2 contain the FAERS data used to populate LAERTES.
I believe 3 was used as the source of the FAERS data meddra / snomed mapping.

I suspect ctgov_drug_trials should also be kept but I'll defer to @rkboyce on that.

**Comment by anthonysena** [comment]
I'm OK with dropping these tables provided that Rich agrees. They are not referenced by the WebAPI.

**Comment by ericaVoss** [comment]
@rkboyce 

Please just bless this list before I move forward:

```{text}
care_site
cdm_source
cohort
cohort_attribute
condition_era
condition_occurrence
death
device_cost
device_exposure
dose_era
drug_cost
drug_era
drug_exposure
fact_relationship
location
measurement
note
observation
observation_period
payer_plan_period
person
procedure_cost
procedure_occurrence
provider
specimen
visit_cost
visit_occurrence
concept_cpt4
ctgov_drug_trials  <---LEE HIGHLIGHTED WE MIGHT NEED
missing_cpt4
multi
target
```

**Comment by rkboyce** [comment]
Please keep ctgov_drug_trials , target (one of the OA tables). I don't see any others that we will need.

**Comment by ericaVoss** [comment]
@leeevans I don't have enough permissions to run this on vocabularyv5.public where the LAERTES data is.

```
DROP TABLE care_site
DROP TABLE cdm_source
DROP TABLE cohort
DROP TABLE cohort_attribute
DROP TABLE condition_era
DROP TABLE condition_occurrence
DROP TABLE death
DROP TABLE device_cost
DROP TABLE device_exposure
DROP TABLE dose_era
DROP TABLE drug_cost
DROP TABLE drug_era
DROP TABLE drug_exposure
DROP TABLE fact_relationship
DROP TABLE location
DROP TABLE measurement
DROP TABLE note
DROP TABLE observation
DROP TABLE observation_period
DROP TABLE payer_plan_period
DROP TABLE person
DROP TABLE procedure_cost
DROP TABLE procedure_occurrence
DROP TABLE provider
DROP TABLE specimen
DROP TABLE visit_cost
DROP TABLE visit_occurrence
DROP TABLE concept_cpt4
DROP TABLE missing_cpt4
DROP TABLE multi
```

**Comment by leeevans** [comment]
@ericaVoss I've dropped these tables in vocabularyv5.public

**Comment by ericaVoss** [comment]
@leeevans  - thank you!  It looks so much cleaner now!
